ARG GOLANG_VERSION="1.19.1"

FROM golang:$GOLANG_VERSION-alpine as builder
RUN apk --no-cache add tzdata
WORKDIR /go/src/github.com/serjs/socks5
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-s' -o ./socks5

FROM scratch
COPY --from=builder /go/src/github.com/serjs/socks5/socks5 /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
HEALTHCHECK --interval=30s --timeout=3s --retries=3 --start-period=10s CMD ["/socks5", "--healthcheck"]
ENTRYPOINT ["/socks5"]
